version: '3.8'

services:
  test:
    image: ${TEST_IMAGE_TAG:-test}
    environment:
      HUB_URL: http://chrome:4444/wd/hub
      PARALLEL_WORKERS: 1 # makes tests run sequentially instead of simultaneously
    command: >
      bash -c "rails test && rails test:system"

networks:
  default:
    external: true
    name: ${SERVICES_NETWORK}