development:
  adapter: postgresql
  encoding: unicode
  host: database
  port: 5432
  username: postgres
  password: postgres
  database: workspace_development

test:
  adapter: postgresql
  encoding: unicode
  host: database
  port: 5432
  username: postgres
  password: postgres
  database: workspace_test